# show 'string mini-shrouds' (8 vols)
/vis/geometry/set/visibility minishroud_lid_43.75x20.00 0 true
/vis/geometry/set/visibility minishroud_lid_47.75x20.00 0 true
/vis/geometry/set/visibility minishroud_lid_50.75x20.00 0 true
/vis/geometry/set/visibility minishroud_lid_53.75x20.00 0 true
/vis/geometry/set/visibility minishroud_tube_44.0 0 true
/vis/geometry/set/visibility minishroud_tube_48.0 0 true
/vis/geometry/set/visibility minishroud_tube_51.0 0 true
/vis/geometry/set/visibility minishroud_tube_54.0 0 true
