# Geant4 viewer of LEGEND-1000:  remage -i l1000-vis.mac   (see README.md)
/RMG/Geometry/GDMLDisableOverlapCheck true
/RMG/Geometry/IncludeGDMLFile l1000.gdml
/run/initialize

/vis/open OGL
/vis/viewer/set/lineSegmentsPerCircle 12
/control/execute l1000-colors.mac
/vis/drawVolume
/vis/viewer/set/style surface
/vis/viewer/set/viewpointThetaPhi 70 20 deg
/vis/viewer/set/upVector 0 0 1
/vis/viewer/set/lightsThetaPhi 70 20 deg
/vis/viewer/set/autoRefresh true
